### ISSUE TITLE
gramps.js requires username and password

### ISSUE THREAD

**Issue by OzarkShepherd** [DavidMStraub/Gramps.js#20] opened 2021-07-09 23:15 UTC
Hi,
What is the username and password supposed to be?  I didn't set up a username or password for the frontend and don't know what to do.  Is the username and password for sqlite?  This is the Gramps-webapi and Gramps.js in a Ubuntu20.04 server in a VM for testing purposes.  Apache2 server, no certificate set up yet because I'm testing it on my computer.
![Screenshot_gramps js](https://user-images.githubusercontent.com/68165701/125143620-cc4fa580-e0e0-11eb-9fa3-13150a5e7cfe.png)

**Comment by OzarkShepherd** [comment] 2021-07-10 00:24
Firefox when I click on submit for random usernames gives a NetworkError when attempting to fetch resource, and the terminal says the below:

>   Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:259:15)
      at ReadStream.onclose (node:internal/streams/end-of-stream:117:38)
      at ReadStream.emit (node:events:339:22)
      at emitCloseNT (node:internal/streams/destroy:169:10)
      at processTicksAndRejections (node:internal/process/task_queues:79:21)

**Comment by DavidMStraub** [comment] 2021-07-10 06:03
Can you please try again? It happens e.g. when the backend cannot be reached. Since the backend is hosted on a free Heroku instance, it goes to sleep after 30 min of inactivity and then always takes some time to wake up again. So it could help trying again after one minute.

Of course, it's not good that there is no informative error message.

**Comment by OzarkShepherd** [comment] 2021-07-10 12:09
Thank you for responding.  In this instance, the backend is supposed to be the Gramps webapi installed on the same VM, running on port 5555.  I suspect I misconfigured the webapi if this is the behavior when the frontend can't reach the backend.  Is Gramps.js configurable?

**Comment by DavidMStraub** [comment] 2021-07-10 20:47
Sorry, I misread your question, I thought this was about the demo server.

By default, the frontend looks for the backend on `localhost:5555`. Check if you can open any of the API endpoints without authentication (e.g. http://localhost:5555/api/metadata/).

**Comment by DavidMStraub** [comment] 2021-08-06 13:11
Is this still an issue?

**Comment by OzarkShepherd** [comment] 2021-08-06 13:39
It is still an issue, but it appears to be an issue with getting the webapi to work with apache2.

**Comment by OzarkShepherd** [comment] 2021-08-06 14:06
the result of `curl http://localhost:5555/api/metadata` is a 404 error.  Same 404 error with `curl http://localhost:5555`.  The webapi is started with `gunicorn -e GRAMPS_API_CONFIG=/usr/local/www/gramps-webapi-0.1/config.cfg --bind localhost:5555 gramps_webapi.wsgi:app`.  I suspect it is an issue with getting apache2 to work with the webapi, specifically configuring python3 apps to be configured properly with apache2.  

I was trying to get it to work with apache2 instead of nginx because I already set up my home server to work with apache2 and didn't want to switch the entire thing to nginx when the webapi reached the production stage.

**Comment by DavidMStraub** [comment] 2021-08-06 18:13
I'm not sure I understand what Apacha has to do with this. If you start gunicorn, you should be able to curl the endpoints from within the VM.

I'll close this issue just because it's not caused by Gramps.js, but feel free to continue posting below or to open an issue at Gramps Web API.

**Closed by DavidMStraub** 2021-08-06 18:13 UTC
